Emoji in code block, fix issue #329
google/devlibrary pull request #335
Opened 2022-02-07 16:35 UTC by jollypolly123

2022-02-09 03:27 UTC, jollypolly123 commented on functions/src/content.ts
> +    const contentList = content.split("```");
Got it—just wondering, why wouldn't we want to do the first change?

2022-02-09 09:50 UTC, samtstern commented on functions/src/content.ts
> +    const contentList = content.split("```");
@jollypolly123 based on my reading of [the spec](https://github.github.com/gfm/#fenced-code-blocks) I think the triple backticks have to be the start of a line or preceded only by whitespace on the line in order to fence off a code block. So it is possible (although unlikely) that you could have a "```" in the middle of content. Therefore just splitting on that character group is not enough.

Simple:
```
Hello
```

Triple backticks at end of line:
```
Hello```
```

Indented
  ```foo
Ok
  ```

2022-02-09 09:53 UTC, samtstern requested changes
Just one more change, thanks!

2022-02-09 09:53 UTC, samtstern commented on functions/src/content.ts
> +      if (val.includes("```")) {
```suggestion
      if (val.trim().startsWith("```")) {
```

2022-02-09 15:06 UTC, jollypolly123 commented on functions/src/content.ts
> +    const contentList = content.split("```");
Gotcha thanks!

2022-02-10 09:52 UTC, samtstern approved these changes

2022-02-10 09:55 UTC, merged

2022-02-10 10:54 UTC, samtstern commented
@jollypolly123 thank you! This should be fixed the next time @techtrailhead deploys the site.