Cloud Champions articles
google/devlibrary pull request #602
Opened 2023-02-02 09:54 UTC by gkindavishal

Fixes b/267254564

2023-02-02 11:40 UTC, 5wathi commented
@gkindavishal : Just the 2 author bio updates. Rest looks good to me.

2023-02-03 10:44 UTC, gkindavishal commented
> @gkindavishal : Just the 2 author bio updates. Rest looks good to me.

Hey @5wathi 
I couldn't find any bio for Paul Jones. Can you help me with that?

2023-02-07 06:20 UTC, 5wathi requested changes

2023-02-07 06:25 UTC, gkindavishal commented on config/authors/rubenszimbres.json
> +  "bio": "",
Updated this

2023-02-07 06:25 UTC, gkindavishal commented on config/authors/paulwilljones.json
> +  "bio": "",
Updated this

2023-02-07 06:26 UTC, gkindavishal commented
@5wathi I've updated the bios, please review the changes and merge PR if it looks good to you

2023-02-07 07:24 UTC, merged

2023-02-07 07:24 UTC, 5wathi commented
done @gkindavishal